### PR TITLE
Add bootloader stub generator for ESP32-C3

### PR DESCRIPTION
**Pull request by duncandrennan**
@rojer 

I managed to get the stub code for the ESP32-C3 to compile and generate a stub. I have no idea whether this will work - it will definitely need a review.

- I think the linker script is okay, but I would like a second set of eyes on this.
- I've hacked wrap_stub.py to accept the machine type of the generated ELF file
- Use duncandrennan/mongoose-os to build the ESP-IDF 4.3-dev docker container

### CODE REVIEW

**Comment by duncandrennan** [comment]
Noting that https://github.com/torvalds/linux/blob/master/include/uapi/linux/elf-em.h lists

`#define EM_RISCV	243	/* RISC-V */`

so the 0xfe is correct in wrap_stub.py

**Comment by rojer** [comment]
looks reasonable overall but you should make sure it works.
i suggest using `mos flash-read` and `mos flash-write` to read and write flash, while we cannot yet generate working firmware.

**Comment by duncandrennan** [comment]
I'll work towards that as the next step.

**Comment by rojer** [comment]
ok, cool

**Pull request merged**
